version: '2'
services:
    assessor-app:
        image: assessor
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://assessor-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    assessor-mssql:
        extends:
            file: mssql.yml
            service: assessor-mssql
